parameters:
    locale: 'pl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Model,Exception}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']